[package]
org = "ballerina"
name = "task"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["task", "job", "schedule"]
repository = "https://github.com/ballerina-platform/module-ballerina-task"
icon = "resources/icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.0"

[[platform.java11.dependency]]
path = "../native/build/libs/task-native-@project.version@.jar"

[[platform.java11.dependency]]
path = "./lib/quartz-@quartz.version@.jar"
