[package]
org = "ballerina"
name = "task"
version = "1.1.2"

[[dependency]]
org = "ballerina"
name = "runtime"
version = "0.5.2"

[[platform.java11.dependency]]
path = "../task-native/build/libs/task-native-1.1.2-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "task"
version = "1.1.2-SNAPSHOT"

[[platform.java11.dependency]]
path = "./lib/quartz-2.3.1.jar"
groupId = "org.quartz-scheduler"
artifactId = "quartz"
version = "2.3.1"
