[project]
org-name = "ballerina"
version = "@toml.version@"

[dependencies]
"ballerina/runtime" = "@stdlib.runtime.version@"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "task"
    version = "@project.version@"
    path = "../task-native/build/libs/task-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["task"]

    [[platform.libraries]]
    artifactId = "quartz"
    version = "2.3.1"
    path = "./lib/quartz-2.3.1.jar"
    groupId = "org.quartz-scheduler"
    modules = ["task"]
