[package]
org = "ballerina"
name = "task"
version = "@toml.version@"

[[dependency]]
org = "ballerina"
name = "runtime"
version = "@stdlib.runtime.version@"

[[platform.java11.dependency]]
path = "../task-native/build/libs/task-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "task"
version = "@project.version@"

[[platform.java11.dependency]]
path = "./lib/quartz-@quartz.version@.jar"
groupId = "org.quartz-scheduler"
artifactId = "quartz"
version = "@quartz.version@"
