[package]
org = "ballerina"
name = "task"
version = "2.0.0"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/task-native-2.0.0.jar"

[[platform.java11.dependency]]
path = "./lib/quartz-2.3.2.jar"
