[package]
org = "ballerina"
name = "task"
version = "2.2.0"
authors = ["Ballerina"]
keywords = ["task", "job", "schedule"]
repository = "https://github.com/ballerina-platform/module-ballerina-task"
license = ["Apache-2.0"]
distribution = "2201.0.0"

[[platform.java11.dependency]]
path = "../native/build/libs/task-native-2.2.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/quartz-2.3.2.jar"
